matrix:
  include:
    - before_script:
        - go get github.com/rooaaar/yaml-translation-utils/same-yaml
        - go get github.com/rooaaar/yaml-translation-utils/yamllinter
      env:
        global:
          secure: kJrUgeEndwUw9M7aJwE+8t6ymqE+0xpIQWwWtJx1NUFiFxoVc7gIUPo4oaoDwFvHf8G4xYVDX7yauN3E6TDFX7NRjcFqXHB8Up3U66c7os+X5dd0zxQ7UOJgETkfuJEKNJjxSe01n6P698SL9JcRLabY073w6Ce6qCGBpJd7SxzlTCoA0UU6WryM3lwqqXHNTubMAlbaHOMvPR56bIY3+s9r9LG6DZWY6>
      language: bash
      notifications:
        email:
          on_failure: change
      script:
        - bash scripts/identical.sh
        - bash scripts/linter.sh
